#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: my-nginx
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        backend:
#          serviceName: my-nginx
#          servicePort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
#  namespace: default
  labels:
    app: my-nginx
spec:
#  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  type: LoadBalancer